apiVersion: v1
kind: Service
metadata:
  name: code-jam-management
  namespace: apis
spec:
  selector:
    app: code-jam-management
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
