kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ghost-storage
  labels:
    app: ghost
  namespace: web
spec:
  storageClassName: linode-block-storage-retain
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 10Gi
