apiVersion: v1
kind: ConfigMap
metadata:
  name: kubewatch-config
  namespace: monitoring
data:
  .kubewatch.yaml: |
    namespace: ""
    handler:
      discord:
        webhook: ""
    ignores:
    - pixels-discord-channel
    - cert-manager-cainjector-leader-election
    - cert-manager-controller
    - ingress-controller-leader-nginx
    - cluster-autoscaler-status
    - ingress-controller-leader
    resource:
      replicationcontroller: true
      clusterrole: true
      serviceaccount: true
      persistentvolume: true
      configmap: true
      namespace: true
      secret: true
      deployment: false
      replicaset: false
      daemonset: false
      services: false
      pod: false
      job: false
      node: false
      ingress: false
